name: import-linter
on:
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  import_linter:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: install dependencies
      run:
        cd src/promptflow-a
        poetry install --no-interaction
        cd ../promptflow-b
        poetry install
    - name: run tests
      run: |
        poetry install --with test
        poetry run lint-imports
      working-directory: ./src/promptflow-a


